#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

#######################
# Actual build stages
#######################
# The following job can be reproduced on any machine in a single line
# with the following:
#
# mvn -U -e -C -V clean package -fae
#######################

jobs:
  include:
    - stage : Validate POM
      script: mvn -U -e -C -B -V help:help -q
    - stage : Fetch Maven Dependencies
      script: mvn -U -e -C -B -V dependency:go-offline
    - stage : Clean (offline)
      script: mvn --offline -e -C -B -V clean
    - stage : Package (offline, no tests)
      script: mvn --offline -e -C -B -V package -fae

#skip install step before each stage by running the /bin/true command
install: true
