#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always


script: 
  - mvn -e -C -B -V clean package -fae

#skip install step before each stage by running the /bin/true command
install: true
